package(default_visibility = ["//visibility:public"])

cc_library(
    name = "api",
    visibility = ["//visibility:public"],
    srcs = ["api.cc"],
    hdrs = ["api.h"],
    deps = ["@opt_tensorflow//:tensorflow"],    
)
